# Generated by Django 4.1.1 on 2022-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_student_age_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age_field',
            field=models.IntegerField(default=0),
        ),
    ]
